### ISSUE TITLE
Save LCD settings

### ISSUE THREAD

**Issue by Homer-Rivera** [crystalfontz/cfa_linux_examples#2]
The provided examples are working on updating my LCD, but if I reboot my server, the LCD changes back to the original screen.  Is there a step that I can add to save the current LCD setting, so it lasts when the server is rebooted?

**Comment by trevinjorg** [comment]
Hello,

Yes, you can send the "store current state as boot state" command and the LCD will maintain that state after a reboot. The command is different depending on which module you're using but it will be detailed in the relevant datasheet.
